Chore/Dashboard-module
ConnectHub/DeliveryHubBE pull request #68
Opened 2023-07-30 22:56 UTC by vsantos1711

Almost selling

2023-07-31 02:24 UTC, mathmartins2 requested changes

2023-07-31 02:24 UTC, mathmartins2 commented on back/src/application/dashboard/dashboard.controller.ts
add filter for the dash by condominium id

2023-07-31 02:24 UTC, mathmartins2 commented on back/src/application/dashboard/dashboard.controller.ts
put await in the promises

2023-07-31 02:24 UTC, mathmartins2 commented on back/src/application/dashboard/dashboard.service.ts
missed types

2023-07-31 02:24 UTC, mathmartins2 commented on back/src/application/dashboard/interfaces/index.ts
```
import {Resident} from '';

export class ChartDataInterface {
  status?: string;
  month?: string;
  orderCount?: number;
  value?: number;
  receiptDateHour?: Date;
  condominiumName?: string;
  addressee?: Resident;
}

```
i think is best type like this!

2023-07-31 02:24 UTC, mathmartins2 commented on back/src/application/dashboard/view-model/dashboard-view-model.ts
> +}
i think is better move all this logic for the services

2023-07-31 02:24 UTC, mathmartins2 commented on back/src/application/dashboard/view-model/dashboard-view-model.ts
> +    ];
i think is better separate this in another file

2023-07-31 02:24 UTC, mathmartins2 commented on back/src/infra/utils/format-month.ts
> +  ];
monthNames is already defined in `back/src/application/dashboard/view-model/dashboard-view-model.ts`

2023-07-31 02:24 UTC, mathmartins2 commented on front/src/components/BarChart/function/index.ts
missed return type

2023-08-11 22:24 UTC, vsantos1711 commented
Mete bronca

2023-08-13 00:50 UTC, mathmartins2 approved these changes

2023-08-13 00:50 UTC, merged